"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"CharacterTheme"
			{
				"ControlName"					"EditablePanel"
				"fieldName"						"CharacterTheme"
				"xpos"							"6"
				"ypos"							"5"
				"zpos"							"0"
				"wide"							"286"
				"tall"							"75"
				"visible"						"1"
				"enabled"						"1"
				"proportionaltoparent"			"1"
				"paintBackground"				"1"
				"paintBackgroundType"			"2"
				"roundedcorners"				"0"
				"bgcolor_override"				"FooterBGBlack"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Character Theme"
					"font"								"ItemFontNameSmallest"
					"centerwrap"						"1"
					"fgcolor"							"Black"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"0"
					"bgcolor_override"					"HudPink"
				}
				
				
				"NotYetSakakiButton"
				{
					"ControlName"					"CExButton"
					"fieldName"						"NotYetSakakiButton"
					"xpos"							"7"
					"ypos"							"16"
					"zpos"							"21"
					"wide"							"65"
					"tall"							"65"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"labelText"						"X"
					"font"							"HudFontGiantBold"
					"textAlignment"					"center"
					"paintBackground"				"0"

					"defaultFgColor_override"		"RedSolid"
					"armedFgColor_override"			"RedSolid"
					"depressedFgColor_override"		"RedSolid"
				}

				"CharacterTheme_Sakaki"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"CharacterTheme_Sakaki"
					"xpos"								"7"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"54"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"Sakaki_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Sakaki_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Sakaki"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"Sakaki_Button"
					{
						"ControlName"						"CExImageButton"
						"fieldName"							"Sakaki_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""						
						"font"								""
						"command"							"engine"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"visible"		"1"
							"wide"			"f20"
							"tall"			"o1"
							"image"			"replay/thumbnails/customizations/sakaki"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}
				}
				
				"NotYetEllepButton"
				{
					"ControlName"					"CExButton"
					"fieldName"						"NotYetEllepButton"
					"xpos"							"4"
					"ypos"							"16"
					"zpos"							"21"
					"wide"							"65"
					"tall"							"65"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"labelText"						"X"
					"font"							"HudFontGiantBold"
					"textAlignment"					"center"
					"paintBackground"				"0"

					"pin_to_sibling"				"CharacterTheme_Sakaki"
					"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"

					"defaultFgColor_override"		"RedSolid"
					"armedFgColor_override"			"RedSolid"
					"depressedFgColor_override"		"RedSolid"
				}

				"CharacterTheme_Ellep"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"CharacterTheme_Ellep"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"54"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"pin_to_sibling"					"CharacterTheme_Sakaki"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"Ellep_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Ellep_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Elizabeth"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"Ellep_Button"
					{
						"ControlName"						"CExImageButton"
						"fieldName"							"Ellep_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"font"								""
						"command"							"engine"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"visible"		"1"
							"wide"			"f20"
							"tall"			"o1"
							"image"			"replay/thumbnails/customizations/ellep"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}
				}
			}
		}
	}
}
