"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"UIFont"
			{
				"ControlName"					"EditablePanel"
				"fieldName"						"UIFont"
				"xpos"							"6"
				"ypos"							"78"
				"zpos"							"0"
				"wide"							"286"
				"tall"							"55"
				"visible"						"1"
				"enabled"						"1"
				"proportionaltoparent"			"1"
				"paintBackground"				"1"
				"paintBackgroundType"			"2"
				"roundedcorners"				"0"
				"bgcolor_override"				"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"In-game font"
					"font"								"ItemFontNameSmallest"
					"centerwrap"						"1"
					"fgcolor"							"Black"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"0"
					"bgcolor_override"					"HudPink"
				}

				"FontTF"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontTF"
					"xpos"								"7"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"

					"FontTF_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontTF_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"TF2"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontTF_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontTF_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_TF"
						"textAlignment"						"center"
						"command"							"engine"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}

				"NotYetLuxiButton"
				{
					"ControlName"					"CExButton"
					"fieldName"						"NotYetLuxiButton"
					"xpos"							"0"
					"ypos"							"12"
					"zpos"							"21"
					"wide"							"65"
					"tall"							"65"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"labelText"						"X"
					"font"							"HudFontGiantBold"
					"textAlignment"					"center"
					"paintBackground"				"0"

					"pin_to_sibling"				"FontLuxi"

					"defaultFgColor_override"		"RedSolid"
					"armedFgColor_override"			"RedSolid"
					"depressedFgColor_override"		"RedSolid"
					"SelectedFgColor_override"		"RedSolid"
				}

				"FontLuxi"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontLuxi"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"

					"pin_to_sibling"					"FontTF"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontLuxi_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontLuxi_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Luxi"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontLuxi_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontLuxi_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Luxi"
						"textAlignment"						"center"
						"command"							"engine"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}

				"NotYetBahnButton"
				{
					"ControlName"					"CExButton"
					"fieldName"						"NotYetBahnButton"
					"xpos"							"0"
					"ypos"							"12"
					"zpos"							"21"
					"wide"							"65"
					"tall"							"65"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"labelText"						"X"
					"font"							"HudFontGiantBold"
					"textAlignment"					"center"
					"paintBackground"				"0"

					"pin_to_sibling"				"FontBahn"

					"defaultFgColor_override"		"RedSolid"
					"armedFgColor_override"			"RedSolid"
					"depressedFgColor_override"		"RedSolid"
					"SelectedFgColor_override"		"RedSolid"
				}

				"FontBahn"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontBahn"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"

					"pin_to_sibling"					"FontLuxi"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontBahn_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontBahn_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Bahnscrift"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontBahn_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontBahn_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Bahn"
						"textAlignment"						"center"
						"command"							"engine"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}
			}
		}
	}
}
