"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"ChatPos"
			{
				"controlName"					"EditablePanel"
				"fieldName"						"ChatPos"
				"xpos"							"7"
				"ypos"							"232"
				"zpos"							"0"
				"wide"							"286"
				"tall"							"48"
				"visible"						"1"
				"enabled"						"1"
				"proportionalToParent"			"1"
				"paintBackground"				"1"
				"paintBackgroundType"			"0"
				"bgColor_override"				"Black"

				"Title"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Chat Position"
					"font"								"ItemFontNameSmallest"
					"centerWrap"						"1"
					"fgColor"							"Black"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"
					"bgColor_override"					"HudPrimary"
				}

				"ChatPosTop"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"ChatPosTop"
					"xpos"								"7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"130"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"

					"ChatTop_Button"
					{
						"controlName"						"CExButton"
						"fieldName"							"ChatTop_Button"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Top Left"						
						"font"								"Customization_Font_TF"
						"textAlignment"						"center"
						"command"							"engine hud_chatpos_top"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}

				"ChatPosBottom"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"ChatPosBottom"
					"xpos"								"rs1-7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"130"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"

					"ChatBottom_Button"
					{
						"controlName"						"CExButton"
						"fieldName"							"ChatBottom_Button"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Bottom Left"						
						"font"								"Customization_Font_TF"
						"textAlignment"						"center"
						"command"							"engine hud_chatpos_bottom"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}
			}
		}
	}
}
