"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"UIFont"
			{
				"ControlName"					"EditablePanel"
				"fieldName"						"UIFont"
				"xpos"							"7"
				"ypos"							"134"
				"zpos"							"0"
				"wide"							"286"
				"tall"							"95"
				"visible"						"1"
				"enabled"						"1"
				"proportionalToParent"			"1"
				"paintBackground"				"1"
				"paintbackgroundtype"			"0"
				"bgcolor_override"				"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"In-game font"
					"font"								"ItemFontNameSmallest"
					"centerWrap"						"1"
					"fgcolor"							"Black"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"HudPrimary"
				}

				"FontTF"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontTF"
					"xpos"								"7"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"FontTF_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontTF_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"TF2"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontTF_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontTF_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_TF"
						"textAlignment"						"center"
						"command"							"engine hud_font_tf"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontBahn"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontBahn"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontTF"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontBahn_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontBahn_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Bahnschrift"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontBahn_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontBahn_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Bahn"
						"textAlignment"						"center"
						"command"							"engine hud_font_bahn"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontLuxi"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontLuxi"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontBahn"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontLuxi_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontLuxi_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Luxi"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontLuxi_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontLuxi_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Luxi"
						"textAlignment"						"center"
						"command"							"engine hud_font_luxi"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontImpress"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontImpress"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontLuxi"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontImpress_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontImpress_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Impress BT"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontImpress_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontImpress_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Impress"
						"textAlignment"						"center"
						"command"							"engine hud_font_impress"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontWing"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontWing"
					"xpos"								"7"
					"ypos"								"54"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"FontWing_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontWing_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"WingDings"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontWing_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontWing_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"0123"						
						"font"								"Customization_Font_Wing"
						"textAlignment"						"center"
						"command"							"engine hud_font_wingding"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontSans"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontSans"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontWing"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontSans_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontSans_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Comic Sans"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontSans_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontSans_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Sans"
						"textAlignment"						"center"
						"command"							"engine hud_font_sans"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontPapaya"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontPapaya"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontSans"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontPapaya_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontPapaya_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Papyrus"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontPapaya_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontPapaya_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Papaya"
						"textAlignment"						"center"
						"command"							"engine hud_font_papyrus"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}

				"FontIosevka"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"FontIosevka"
					"xpos"								"4"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"65"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintbackgroundtype"				"0"

					"pin_to_sibling"					"FontPapaya"
					"pin_corner_to_sibling"				"PIN_BOTTOMLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"

					"FontIosevka_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"FontIosevka_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseInputEnabled"					"0"
						"proportionalToParent"				"1"
						"font"								"ItemFontNameSmallest"
						"labelText"							"Iosevka"
						"textAlignment"						"center"
						"fgcolor"							"White"
						"paintBackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"FontIosevka_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"FontIosevka_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"1234..."						
						"font"								"Customization_Font_Iosevka"
						"textAlignment"						"center"
						"command"							"engine hud_font_iosevka"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultbgcolor_override"			"DarkerBlack"
					}
				}
			}
		}
	}
}
