"resource/ui/#customizations/hud_customization_frame.res"
{
	"SafeMode"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"SafeMode"
		"xpos"						"314"
		"ypos"						"94"
		"wide"						"300"
		"tall"						"316"
		"zpos"						"55"
		"visible"					"1"
		"enabled"					"1"
		"proportionalToParent"		"1"
		"bgcolor_override"			"DarkerBlack"
		"paintbackgroundtype"	"2"
		
		"Title"
		{
			"ControlName"					"CExLabel"
			"fieldName"						"Title"
			"xpos"							"cs-0.5"			
			"ypos"							"0"
			"zpos"							"-1"
			"wide"							"f0"
			"tall"							"25"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"#TF_OptionCategory_HUD"
			"font"							"HudFontMediumSmallBold"
			"textAlignment"					"west"
			"textinsetX"					"10"
			"textinsetY"					"0"
			"fgcolor"						"White"
			"paintBackground"				"1"
			"paintbackgroundtype"			"2"
			"roundedCorners"				"3"
			"bgcolor_override"				"DarkBlack"
		}

		"Footer"
		{
			"ControlName"					"CExLabel"
			"fieldName"						"Footer"
			"xpos"							"cs-0.5"
			"ypos"							"rs1"
			"zpos"							"-1"
			"wide"							"f0"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"#rose_HudNameVersion"
			"font"							"DefaultBahnMedium"
			"textAlignment"					"center"
			"textinsetX"					"0"
			"fgcolor"						"White"
			"paintBackground"				"1"
			"paintbackgroundtype"			"2"
			"roundedCorners"				"12"
			"bgcolor_override"				"DarkBlack"
		}

		"BottomBGHighlight"
		{
			"ControlName"	"Panel"
			"fieldName"		"BottomBGHighlight"
			"xpos"			"0"
			"ypos"			"2"
			"zpos"			"0"
			"wide"			"f0"
			"tall"			"2"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"	"HudPrimary"
			"pin_to_sibling"	"Footer"
		}

		"GitButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"GitButton"
			"xpos"							"0"
			"ypos"							"rs1"
			"zpos"							"20"
			"wide"							"75"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"GitHub"
			"font"							"DefaultBahn"
			"textAlignment"					"west"
			"textinsetX"					"10"
			"allcaps"						"1"
			"command"						"url https://github.com/RoseyLemonz/rosehud"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"defaultbgcolor_override"		"TrueBlack"
			"armedbgcolor_override"			"White"
			"depressedfgcolor_override"		"White"

			"defaultfgcolor_override"		"White"
			"armedfgcolor_override"			"TrueBlack"
			"depressedfgcolor_override"		"255 255 255 255"

			"roundedCorners"				"4"

			"image_drawcolor"	"255 255 255 255"
			"image_armedcolor"	"0 0 0 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"rs1-5"
				"ypos"			"cs-0.5"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
				"proportionalToParent"	"1"
				"image"			"replay/thumbnails/menu/githublogo"
			}
		}

		"DiscordButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"DiscordButton"
			"xpos"							"rs1"
			"ypos"							"rs1"
			"zpos"							"21"
			"wide"							"75"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"Discord"
			"font"							"DefaultBahn"
			"textAlignment"					"east"
			"textinsetX"					"15"
			"allcaps"						"1"
			"command"						"url https://discord.gg/p5JV3k5CfE"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"defaultbgcolor_override"		"88 101 242 255"
			"armedbgcolor_override"			"224 227 255 255"
			"depressedfgcolor_override"		"224 227 255 255"

			"defaultfgcolor_override"		"224 227 255 255"
			"armedfgcolor_override"			"TrueBlack"
			"depressedfgcolor_override"		"255 255 255 255"

			"roundedCorners"				"8"

			"image_drawcolor"	"224 227 255 255"
			"image_armedcolor"	"0 0 0 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"5"
				"ypos"			"cs-0.5"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
				"proportionalToParent"	"1"
				"image"			"replay/thumbnails/menu/discordlogo"
			}
		}

		"ApplyButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"ApplyButton"
			"xpos"							"6"
			"ypos"							"29"
			"zpos"							"20"
			"wide"							"96"
			"tall"							"22"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"labelText"						"#IT_Apply"
			"font"							"DefaultBahn"
			"textAlignment"					"center"
			"allcaps"						"1"
			"command"						"engine cl_mainmenu_safemode 0; mat_queue_mode -1; hud_reloadscheme"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"roundedCorners"				"0"
		}

		"ResetAllButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"ResetAllButton"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"21"
			"wide"							"96"
			"tall"							"22"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"labelText"						"#GameUI_UseDefaults"
			"font"							"DefaultBahn"
			"textAlignment"					"center"
			"allcaps"						"1"
			"command"						"engine customization_reset"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"roundedCorners"				"0"

			"pin_to_sibling"				"ApplyButton"
			"pin_corner_to_sibling"			"PIN_TOPLEFT"
			"pin_to_sibling_corner"			"PIN_TOPRIGHT"

			"border_default"	"MainMenuSubButtonBorder"
		}

		"ReloadGameButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"ReloadGameButton"
			"xpos"							"-1"
			"ypos"							"0"
			"zpos"							"21"
			"wide"							"97"
			"tall"							"22"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"labelText"						"#Vote_RestartGame"
			"font"							"DefaultBahn"
			"textAlignment"					"center"
			"allcaps"						"1"
			"command"						"engine gameui_allowescape; mat_queue_mode -1; gamemenucommand RestartWithNewLanguage"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"roundedCorners"				"0"

			"pin_to_sibling"				"ResetAllButton"
			"pin_corner_to_sibling"			"PIN_TOPLEFT"
			"pin_to_sibling_corner"			"PIN_TOPRIGHT"
		}

		"CloseButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"CloseButton"
			"xpos"							"rs1-5"
			"ypos"							"3"
			"zpos"							"21"
			"wide"							"18"
			"tall"							"18"
			"visible"						"1"
			"enabled"						"1"
			"proportionalToParent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"("
			"font"							"HudMenuIco"
			"textAlignment"					"center"
			"command"						"engine cl_mainmenu_safemode 0; mat_queue_mode -1"
			"actionSignalLevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"

			"armedfgcolor_override"			"HudPrimary"
			"depressedfgcolor_override"		"HudPrimaryLight"
			
			"paintBackground"	"0"

			"roundedCorners"				"0"
		}
	}
}
