"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"TeamIndicator"
			{
				"controlName"					"EditablePanel"
				"fieldName"						"TeamIndicator"
				"xpos"							"7"
				"ypos"							"284"
				"zpos"							"0"
				"wide"							"286"
				"tall"							"48"
				"visible"						"1"
				"enabled"						"1"
				"proportionalToParent"			"1"
				"paintBackground"				"1"
				"paintBackgroundType"			"0"
				"bgColor_override"				"Black"

				"Title"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Team Indicator"
					"font"								"ItemFontNameSmallest"
					"centerWrap"						"1"
					"fgColor"							"Black"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"
					"bgColor_override"					"HudPrimary"
				}

				"IndicatorOn"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IndicatorOn"
					"xpos"								"7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"42"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"0"

					"IndicatorOnButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IndicatorOnButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"On"						
						"font"								"HudFontSmallBold"
						"textAlignment"						"center"
						"command"							"engine hud_indicator_visible"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"HudBonusDark"
						"armedBgColor_override"				"HudBonusLight"
						"depressedFgColor_override"			"HudBonus"
					}
				}

				"IndicatorOff"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IndicatorOff"
					"xpos"								"52"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"42"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"0"

					"IndicatorOffButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IndicatorOffButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Off"						
						"font"								"HudFontSmallBold"
						"textAlignment"						"center"
						"command"							"engine hud_indicator_invis"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"HudNegatDark"
						"armedBgColor_override"				"HudNegatLight"
						"depressedFgColor_override"			"HudNegat"
					}
				}

				"IndicatorLeft"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IndicatorLeft"
					"xpos"								"cs-0.5"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"88"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"

					"IndicatorLeftButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IndicatorLeftButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Bottom Left"
						"font"								"HudFontSmallestBold"
						"textAlignment"						"center"
						"command"							"engine hud_indicator_left; hud_indicator_visible"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}
				"IndicatorRight"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IndicatorRight"
					"xpos"								"rs1-7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"88"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"

					"IndicatorRightButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IndicatorRightButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Bottom Right"
						"font"								"HudFontSmallestBold"
						"textAlignment"						"center"
						"command"							"engine hud_indicator_right; hud_indicator_visible"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"DarkerBlack"
					}
				}
			}
		}
	}
}
