"resource/ui/#customizations/hud_customization_health.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"HealthIcon"
			{
				"controlName"					"EditablePanel"
				"fieldName"						"HealthIcon"
				"xpos"							"cs-0.5"
				"ypos"							"336"
				"zpos"							"0"
				"wide"							"94"
				"tall"							"48"
				"visible"						"1"
				"enabled"						"1"
				"proportionalToParent"			"1"
				"paintBackground"				"1"
				"paintBackgroundType"			"0"
				"bgColor_override"				"Black"

				"Title"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Health Icon"
					"font"								"ItemFontNameSmallest"
					"centerWrap"						"1"
					"fgColor"							"Black"
					"paintBackground"					"1"
					"paintBackgroundType"				"0"
					"bgColor_override"					"HudPrimary"
				}

				"IconOn"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IconOn"
					"xpos"								"7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"39"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"0"

					"IconOnButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IconOnButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"On"						
						"font"								"HudFontSmallBold"
						"textAlignment"						"center"
						"command"							"engine hud_healthicon_on"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"HudBonusDark"
						"armedBgColor_override"				"HudBonusLight"
						"depressedBgColor_override"			"HudBonus"
					}
				}

				"IconOff"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"IconOff"
					"xpos"								"rs1-7"
					"ypos"								"20"
					"zpos"								"20"
					"wide"								"39"
					"tall"								"35"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"0"

					"IconOffButton"
					{
						"controlName"						"CExButton"
						"fieldName"							"IconOffButton"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"labelText"							"Off"						
						"font"								"HudFontSmallBold"
						"textAlignment"						"center"
						"command"							"engine hud_healthicon_off"
						"actionSignalLevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
						"defaultBgColor_override"			"HudNegatDark"
						"armedBgColor_override"				"HudNegatLight"
						"depressedBgColor_override"			"HudNegat"
					}
				}
			}
		}
	}
}
