"Resource/UI/HudAmmoWeapons.res"
{
	"HudAmmoIco"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudAmmoIco"
		"xpos"			"cs-0.5+215"
		"ypos"			"r122"
		"zpos"			"2"
		"wide"			"38"
		"tall"			"38"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/ammo/ammo_icon"
		"scaleImage"	"1"			
	}
	"HudAmmoIcoOverlay"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudAmmoIcoOverlay"
		"zpos"			"3"
		"wide"			"38"
		"tall"			"38"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/ammo/ammo_icon_over"
		"drawcolor"		"HudPrimaryDark"
		"scaleImage"	"1"			
		"pin_to_sibling"	"HudAmmoIco"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"cs-0.5+215"
		"ypos"			"r123"
		"zpos"			"2"
		"wide"			"40"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/ammo/ammo_icon_bonus"
		"drawcolor"		"255 0 0 255"
		"scaleImage"	"1"
		"alpha"			"0"	
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"HudValue"
		"xpos"			"cs-0.5+115"
		"ypos"			"r127"
		"zpos"			"5"
		"wide"			"95"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		"fgcolor_override"	"HudPrimaryLight"
	}		

	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"HudValue"
		"fgcolor"		"Black"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"95"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		"pin_to_sibling"	"AmmoInClip"
		"fgcolor_override"	"Black"
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"HudAmmoReserve"
		"xpos"			"cs-0.5+185"
		"ypos"			"r130"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
		"fgcolor_override"	"HudPrimaryTransparent"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"HudAmmoReserve"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
		"pin_to_sibling"	"AmmoInReserve"
		"fgcolor_override"	"TransparentBlack"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"HudValue"
		"xpos"			"cs-0.5+125"
		"ypos"			"r127"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"		
		"labelText"		"%Ammo%"
		"fgcolor_override"	"HudPrimaryLight"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"HudValue"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"		
		"labelText"		"%Ammo%"
		"pin_to_sibling"	"AmmoNoClip"
		"fgcolor_override"	"Black"
	}							
}
