"Resource/UI/HudPlayerHealth.res"
{	
	// player health data
	"HudPlayerHealth"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"HudPlayerHealth"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"35"
		"HealthDeathWarning"	"0.49"
		"HealthDeathWarningColor"	"HUDDeathWarning"
	}	

	"TheMeasuringStickTM"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"TheMeasuringStickTM"
		"xpos"			"cs-0.5"
		"ypos"			"r160"
		"wide"			"450"
		"tall"			"5"
		"visible"		"0"
		"enabled"		"1"
		"fillColor"		"255 255 255 255"
	}	
	
	"TeamIndicator"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"TeamIndicator"
		"xpos"			"0"
		"ypos"			"rs1"
		"zpos"			"500"
		"wide"			"70"
		"tall"			"o1"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"
		"teambg_1"		"replay/thumbnails/blank"
		"teambg_2"		"replay/thumbnails/hud/redcorner"
		"teambg_3"		"replay/thumbnails/hud/blucorner"
	}

	"RandomTextTestLabel"
	{
		"controlName"	"Label"
		"fieldName"		"RandomTextTestLabel"
		"xpos"			"cs-0.5"
		"ypos"			"cs-0.5"
		"zpos"			"100"
		"wide"			"p0.5"
		"tall"			"p0.5"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"    "
		"textAlignment"	"center"	
		"font"			"HudTargetIDIcons"
		"fgColor"		"HudPrimaryLight"
	}

	"PlayerCharaImage"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"PlayerCharaImage"
		"xpos"			"cs-0.5-150"
		"ypos"			"r78"
		"zpos"			"2"
		"wide"			"90"
		"tall"			"o1"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"replay/thumbnails/characters/sakaki"
	}

	"PlayerCharaImageHurt"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"PlayerCharaImageHurt"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"90"
		"tall"			"o1"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"alpha"			"0"
		"image"			"replay/thumbnails/characters/sakakihurt"
		"pin_to_sibling"	"PlayerCharaImage"
	}

	"PlayerCharaImageBonus"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"PlayerCharaImageBonus"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"90"
		"tall"			"o1"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"alpha"			"0"
		"image"			"replay/thumbnails/characters/sakakispin"
		"pin_to_sibling"	"PlayerCharaImage"
	}

	"PlayerStatusHealthImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImage"
		"xpos"			"cs-0.5-215"
		"ypos"			"r120"
		"zpos"			"4"
		"wide"			"35"
		"tall"			"35"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
	}		
	"PlayerStatusHealthAdditive"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthAdditive"
		"zpos"			"5"
		"wide"			"35"
		"tall"			"35"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/health_color_additive"
		"scaleImage"	"1"
		"pin_to_sibling"	"PlayerStatusHealthImage"
	}
	"PlayerStatusHealthAdditiveOverlay"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthAdditiveOverlay"
		"zpos"			"6"
		"wide"			"35"
		"tall"			"35"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/health_color_over"
		"drawColor"		"HudPrimaryDark"
		"scaleImage"	"1"
		"pin_to_sibling"	"PlayerStatusHealthImage"
	}
	"PlayerStatusHealthImageBG"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"xpos"			"2"
		"ypos"			"2"
		"zpos"			"3"
		"wide"			"39"
		"tall"			"39"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/health_bg"
		"scaleImage"	"1"	
		"pin_to_sibling"	"PlayerStatusHealthImage"
	}	
	"PlayerStatusHealthBonusImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"cs-0.5-215"
		"ypos"			"r122"
		"zpos"			"2"
		"wide"			"39"
		"tall"			"39"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/health_over_bg"
		"scaleImage"	"1"	
	}
	"PlayerStatusHealthValue"
	{
		"controlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValue"
		"xpos"			"cs-0.5-120"
		"ypos"			"r127"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"	"west"	
		"font"			"HudValue"
		"fgColor"		"HudPrimaryLight"
	}

	"PlayerStatusHealthValueShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueShadow"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"4"
		"wide"			"120"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"	"west"	
		"font"			"HudValue"
		"fgColor"		"Black"
		"pin_to_sibling"	"PlayerStatusHealthValue"
	}

	"PlayerStatusMaxHealthValue"
	{
		"controlName"	"CExLabel"
		"fieldName"		"PlayerStatusMaxHealthValue"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"6"
		"wide"			"50"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%MaxHealth%"
		"textAlignment"	"west"	
		"font"			"HudHealthMax"
		"fgColor"		"HudPrimaryTransparent"
		"pin_to_sibling"	"PlayerStatusHealthValue"
	}
	"PlayerStatusMaxHealthValueShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"PlayerStatusMaxHealthValueShadow"
		"xpos"			"-1"
		"ypos"			"9"
		"zpos"			"6"
		"wide"			"50"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%MaxHealth%"
		"textAlignment"	"west"	
		"font"			"HudHealthMax"
		"fgColor"		"TransparentBlack"
		"pin_to_sibling"	"PlayerStatusHealthValue"
	}

	"PlayerStatusPin"
	{
		"controlName"	"Panel"
		"xpos"			"cs-0.5-27"
		"ypos"			"r75"
		"wide"			"0"
		"visible"		"0"
	}

	"PlayerStatusBleedImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusBleedImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusHookBleedImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHookBleedImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop_grapple"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusMilkImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMilkImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusGasImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusGasImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/covered_in_gas"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusMarkedForDeathImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMarkedForDeathImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/marked_for_death"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusMarkedForDeathSilentImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMarkedForDeathSilentImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/marked_for_death"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_MedicUberBulletResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberBulletResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_MedicUberBlastResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberBlastResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_explosion_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_MedicUberFireResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberFireResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_fire_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}

	"PlayerStatus_MedicSmallBulletResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallBulletResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_MedicSmallBlastResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallBlastResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_explosion_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_MedicSmallFireResistImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallFireResistImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_fire_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	

	"PlayerStatus_WheelOfDoom"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_WheelOfDoom"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../signs/death_wheel_whammy"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}

	"PlayerStatus_SoldierOffenseBuff"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierOffenseBuff"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}

	"PlayerStatus_SoldierDefenseBuff"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierDefenseBuff"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}

	"PlayerStatus_SoldierHealOnHitBuff"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierHealOnHitBuff"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_SpyMarked"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SpyMarked"
		"xpos"			"115"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			""
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_Parachute"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_Parachute"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			""
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneStrength"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneStrength"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_strength_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneHaste"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneHaste"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_haste_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneRegen"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneRegen"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_regen_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneResist"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneResist"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_resist_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneVampire"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneVampire"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_vampire_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneReflect"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneReflect"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_reflect_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RunePrecision"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RunePrecision"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_precision_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneAgility"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneAgility"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_agility_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneKnockout"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneKnockout"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_knockout_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneKing"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneKing"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_king_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RunePlague"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RunePlague"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_plague_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatus_RuneSupernova"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneSupernova"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_supernova_hud"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
	"PlayerStatusSlowed"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"PlayerStatusSlowed"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/slowed"
		"fgColor"		"TanDark"
		"pin_to_sibling"	"PlayerStatusPin"
	}
}
