"Resource/UI/CharInfoPanel.res"
{
	"character_info"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"character_info"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"settitlebarvisible"	"1"
		"PaintBackgroundType"	"0"
		"bgcolor_override"				"46 43 42 0"
		"infocus_bgcolor_override"		"46 43 42 0"
		"outoffocus_bgcolor_override"	"46 43 42 0"
		
		"title"			"#CharInfoAndSetup"
		"title_font"	"HudFontMediumBold"
		"titletextinsetX"	"40"
		"titletextinsetY"	"0"
		"titlebarfgcolor_override"				"200 187 161 255"
		"titlebardisabledfgcolor_override"		"200 187 161 255"
		"titlebarbgcolor_override"				"46 43 42 255"
		
		"clientinsetx_override"			"0"
		"sheetinset_bottom"				"40"
	}
	
	"BackgroundHeader"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"BackgroundHeader"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"120"
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"paintBackgroundType"	"0"
		"bgColor_override"		"DarkestGray"
	}		
	"BackgroundFooter"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"BackgroundFooter"
		"xpos"			"-5"
		"ypos"			"420"
		"zpos"			"40"
		"wide"			"f-5"
		"tall"			"f0"
		"visible"		"1"
		"enabled"		"1"
		"bgColor_override"		"DarkerBlack"
		"border"				"FooterWithAccent"
	}			
	
	"Sheet"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"Sheet"
		"tabxindent"	"36"
		"tabxdelta"		"5"
		"tabwidth"		"220"
		"tabheight"			"26"
		"transition_time"	"0"
		"yoffset"			"6"
		
		"HeaderLine"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"HeaderLine"
			"xpos"			"0"
			"ypos"			"31"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"1"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"	"DarkGray"
		}					
		
		"tabskv"
		{
			"textinsetx"				"30"
			"proportionaltoparent"		"1"
			"font"						"HudFontMediumSmallBold"
			"selectedcolor"				"White"
			"unselectedcolor"			"DarkGray"
			"paintbackground"			"1"
			"activeborder_override"		"BPActiveBorder"
			"normalborder_override" 	"BPInactiveBorder"
		}
	}		
	"BackButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"BackButton"
		"xpos"			"36"
		"ypos"			"rs1-18"
		"zpos"			"45"
		"wide"			"120"
		"tall"			"26"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#rose_Back"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"back"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}		
	
	"NotificationsPresentPanel"
	{
		"ControlName"	"CNotificationsPresentPanel"
		"fieldName"		"NotificationsPresentPanel"
		"xpos"			"r200"
		"ypos"			"10"
		"zpos"			"10000"
		"wide"			"190"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
	}
}
