"Resource/UI/CharInfoLoadoutSubPanel.res"
{
	"CharInfoLoadoutSubPanel"
	{
		"ControlName"	"Frame"
		"fieldName"		"CharInfoLoadoutSubPanel"
		"xpos"			"0"
		"ypos"			"40"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"0"
		"bgcolor_override"		"DarkBlack"

		"selectlabely_default"		"44"
		"selectlabely_onchanges"	"44"

		"class_ypos"				"0"
		"class_xdelta"				"0"
		"class_wide_min"			"0"
		"class_wide_max"			"0"
		"class_tall_min"			"0"
		"class_tall_max"			"0"
		"class_distance_min"		"0"
		"class_distance_max"		"0"
		"itemcountcolor"			""
		"itemcountcolor_noitems"	""
	}

	"scout"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"scout"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomScout"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomScout"
		"xpos"						"c-290"
		"ypos"						"c-140"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&1"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout scout"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"
	}
	"TitleScout"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleScout"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Scout"
		"textAlignment"				"center"
		"xpos"						"c-290"
		"ypos"						"c-80"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
	}

	"soldier"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"soldier"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomSoldier"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomSoldier"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&2"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout soldier"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomScout"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleSoldier"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleSoldier"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Soldier"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleScout"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"pyro"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"pyro"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomPyro"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomPyro"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&3"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets" 	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout pyro"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomSoldier"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitlePyro"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitlePyro"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Pyro"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleSoldier"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"demoman"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"demoman"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomDemoman"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomDemoman"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&4"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout demoman"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomPyro"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleDemoman"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleDemoman"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Demoman"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitlePyro"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"heavyweapons"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"heavyweapons"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomHeavy"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomHeavy"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&5"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets" 	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout heavy"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomDemoman"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleHeavy"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleHeavy"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_HWGuy"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleDemoman"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"engineer"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"engineer"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomEngineer"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomEngineer"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&6"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets" 	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout engineer"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomHeavy"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleEngineer"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleEngineer"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Engineer"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleHeavy"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"medic"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"medic"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomMedic"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomMedic"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&7"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout medic"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomEngineer"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleMedic"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleMedic"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Medic"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleEngineer"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"sniper"
	{
		"ControlName"				"ImageButton"
		"fieldName"					"sniper"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomSniper"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomSniper"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&8"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets" 	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout sniper"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomMedic"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleSniper"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleSniper"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Sniper"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleMedic"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"spy"
	{
		"ControlName"				"ImageButton"
		"xpos"						"9999"
		"wide"						"0"
		"activeimage"				""
		"inactiveimage"				""
	}
	"CustomSpy"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomSpy"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"55"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"&9"
		"font"						"MenuClassSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"loadout spy"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomSniper"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleSpy"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleSpy"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TF_Spy"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"55"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleSniper"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	
	"ShowBackpackButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowBackpackButton"
		"xpos"				"9999"
		"wide"				"0"
		"activeimage"		""
		"inactiveimage"		""
	}	
	"ShowBackpackLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowBackpackLabel"
		"xpos"			"9999"
		"wide"			"0"
	}

	"CustomBackpack"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomBackpack"
		"xpos"						"c-185"
		"ypos"						"c-40"
		"zpos"						"10"
		"wide"						"65"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"3"
		"font"						"MenuMiscSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"backpack"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"
	}
	"TitleBackpack"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleBackpack"
		"font"						"HudFontSmallestBold"
		"labelText"					"#BackpackTitle"
		"textAlignment"				"center"
		"xpos"						"c-185"
		"ypos"						"c20"
		"zpos"						"5"
		"wide"						"65"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
	}

	"ShowCraftingButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowCraftingButton"
		"xpos"				"9999"
		"wide"				"0"
		"activeimage"		""
		"inactiveimage"		""
	}
	"ShowCraftingLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowCraftingLabel"
		"xpos"			"9999"
		"wide"			"0"
	}

	"CustomCrafting"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomCrafting"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"65"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"B"
		"font"						"MenuMiscSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"crafting"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomBackpack"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleCrafting"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleCrafting"
		"font"						"HudFontSmallestBold"
		"labelText"					"#CraftingExplanation_Title"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"65"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleBackpack"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"ShowArmoryButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowArmoryButton"
		"xpos"				"9999"
		"wide"				"0"
		"activeimage"		""
		"inactiveimage"		""
	}	
	"ShowArmoryLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowArmoryLabel"
		"xpos"			"9999"
		"wide"			"0"
	}

	"CustomArmory"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomArmory"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"65"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					";"
		"font"						"MenuMiscSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"armory"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomCrafting"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleArmory"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleArmory"
		"font"						"HudFontSmallestBold"
		"labelText"					"#Armory"
		"centerwrap"				"1"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"65"
		"tall"						"25"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleCrafting"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"ShowTradeButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowTradeButton"
		"xpos"				"9999"
		"wide"				"0"
		"activeimage"		""
		"inactiveimage"		""
	}	
	"ShowTradeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowTradeLabel"
		"xpos"			"9999"
		"wide"			"0"
	}

	"CustomTrade"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomTrade"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"65"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"6"
		"font"						"MenuMiscSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"trading"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomArmory"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitleTrading"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitleTrading"
		"font"						"HudFontSmallestBold"
		"labelText"					"#TradingExplanation_Title"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"65"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleArmory"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}

	"ShowPaintkitsButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowPaintkitsButton"
		"xpos"				"9999"
		"wide"				"0"
		"activeimage"		""
		"inactiveimage"		""
	}	
	"ShowPaintkitsLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ShowPaintkitsLabel"
		"xpos"				"9999"
		"wide"				"0"
	}

	"CustomPaintkit"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"CustomPaintkit"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"65"
		"tall"						"70"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"C"
		"font"						"MenuMiscSelect"
		"textAlignment"				"center"
		"use_proportional_insets"	"1"
		"default"					"0"
		"paintbackground"			"0"
		"Command"					"paintkit_preview"
		"paintbackground"			"0"

		"armedFgColor_override" 	"HudPrimary"
		"depressedFgColor_override" "HudPrimaryDark"

		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"

		"pin_to_sibling"			"CustomTrade"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	"TitlePaintkit"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"TitlePaintkit"
		"font"						"HudFontSmallestBold"
		"labelText"					"#PaintkitTitle"
		"textAlignment"				"center"
		"xpos"						"10"
		"ypos"						"0"
		"zpos"						"5"
		"wide"						"65"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"

		"pin_to_sibling"			"TitleTrading"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"PIN_TOPRIGHT"
	}
	
	"ClassLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"ClassLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"classname"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"200"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"ItemsLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemsLabel"
		"font"			"HudFontSmall"
		"labelText"		"classname"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"215"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor"		"117 107 94 255"
		"centerwrap"	"1"
	}
	
	"NoSteamLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NoSteamLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#NoSteamNoItems"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"250"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	"NoGCLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NoGCLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#NoGCNoItems"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"250"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	"SelectLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SelectLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#SelectClassLoadout"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"300"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "DarkGray"
	}
	"LoadoutChangesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"LoadoutChangesLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#LoadoutChangesUpdate"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"30"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "HudPrimary"
	}
	
	"class_loadout_panel"
	{
		"ControlName"		"CClassLoadoutPanel"
		"fieldName"			"class_loadout_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"500"
		"visible"			"0"
	}
	"backpack_panel"
	{
		"ControlName"		"CBackpackPanel"
		"fieldName"			"backpack_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"500"
		"visible"			"0"
	}
	
	"armory_panel"
	{
		"ControlName"		"CArmoryPanel"
		"fieldName"			"armory_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"500"
		"visible"			"0"
	}

	"InspectionPanel"
	{
		"fieldName"		"InspectionPanel"
		"xpos"			"cs-0.5"
		"ypos"			"0"
		"zpos"			"2000"
		"wide"			"f0"
		"tall"			"f100"
		"visible"		"0"
		"proportionaltoparent"	"1"
		"bgcolor_override"	"30 25 25 245"
	}


	"ShowExplanationsButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ShowExplanationsButton"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"StartExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"StartExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}	
	
	"BackpackExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"BackpackExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}	
	
	"CraftingExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"CraftingExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}	
	
	"ArmoryExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"ArmoryExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"TradingExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"TradingExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"PatternsExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"PatternsExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"ExplanationExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"ExplanationExplanation"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}	
}
