"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"cs-0.5+205"
		"ypos"			"r122"
		"zpos"			"2"
		"wide"			"38"
		"tall"			"38"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hud/ammoiconsakaki"
		"scaleImage"	"1"			
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"cs-0.5+205"
		"ypos"			"r123"
		"zpos"			"2"
		"wide"			"40"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hud/ammoiconbonus"
		"drawcolor"		"255 0 0 255"
		"scaleImage"	"1"
		"alpha"			"0"	
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"HudValue"
		"fgcolor"		"HudPink"
		"xpos"			"cs-0.5+100"
		"ypos"			"r120"
		"zpos"			"5"
		"wide"			"95"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
	}		

	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"HudValue"
		"fgcolor"		"Black"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"95"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		"pin_to_sibling"	"AmmoInClip"
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"HudAmmoReserve"
		"fgcolor"		"HudLightPink"
		"xpos"			"cs-0.5+170"
		"ypos"			"r118"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"HudAmmoReserve"
		"fgcolor"		"Black"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
		"pin_to_sibling"	"AmmoInReserve"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"HudValue"
		"fgcolor"		"HudPink"
		"xpos"			"cs-0.5+120"
		"ypos"			"r120"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"HudValue"
		"fgcolor"		"Black"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"		
		"labelText"		"%Ammo%"
		"pin_to_sibling"	"AmmoNoClip"
	}							
}
