#base "textpanel_base.res"
"resource/ui/arenateammenu.res"
{
	"team"
	{
		"ControlName"	"CTeamMenu"
		"fieldName"		"team"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}

	"SysMenu"
	{
		"ControlName"	"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"64"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"teambutton2"
	{
		"ControlName"	"CExButton"
		"fieldName"		"teambutton2"
		"xpos"			"cs-0.5"
		"ypos"			"150"
		"wide"			"220"
		"tall"			"80"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"( &1 )"
		"textAlignment"	"center"
		"command"		"jointeam spectate"
		"font"			"HudFontBiggerBold"
		
		"defaultbgcolor_override" 	"TransparentBlack"
		"armedbgcolor_override"		"HudPrimary"
		"depressedbgcolor_override" "HudPrimaryDark"

		"defaultfgcolor_override" 	"White"
		"armedfgcolor_override"		"Black"
		"depressedfgcolor_override" "HudPrimaryLight"
	}
	
	"teambutton3"
	{
		"ControlName"	"CExButton"
		"fieldName"		"teambutton3"
		"xpos"			"cs-0.5"
		"ypos"			"300"
		"wide"			"160"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"( &2 )"
		"textAlignment"	"center"
		"command"		"jointeam spectatearena"
		"font"			"HudFontMediumBold"
		
		"defaultbgcolor_override" 	"TransparentBlack"
		"armedbgcolor_override"		"HudPrimary"
		"depressedbgcolor_override" "HudPrimaryDark"

		"defaultfgcolor_override" 	"White"
		"armedfgcolor_override"		"Black"
		"depressedfgcolor_override" "HudPrimaryLight"
	}
	
	"CancelButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"			"0"
		"ypos"			"rs1"
		"zpos"			"6"
		"wide"			"f0"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#rose_Cancel"
		"textAlignment"	"center"
		"command"		"cancelmenu"
		"font"			"HudFontSmallBold"
		"roundedcorners"	"0"
		"defaultBgColor_override"	"DarkerBlack"
	}
		
	"TeamMenuAuto"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuAuto"
		"xpos"			"0"
		"ypos"			"110"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Menu_Fight"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontBiggerBold"
		"fgcolor"		"White"
	}
	"TeamMenuAutoShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuAutoShadow"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Menu_Fight"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontBiggerBold"
		"fgcolor"		"Black"
		"pin_to_sibling"	"TeamMenuAuto"
	}
	
	"TeamMenuSpectate"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuSpectate"
		"xpos"			"0"
		"ypos"			"255"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Spectate"
		"textAlignment"	"north"
		"wrap"			"0"
		"font"			"HudFontMediumBold"
		"fgcolor"		"White"
	}

	"TeamMenuSpectateShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuSpectateShadow"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Spectate"
		"textAlignment"	"north"
		"wrap"			"0"
		"font"			"HudFontMediumBold"
		"fgcolor"		"Black"
		"pin_to_sibling"	"TeamMenuSpectate"
	}

	"BGDarken"
	{
		"ControlName"	"Panel"
		"fieldName"		"BGDarken"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"ChalkBG"
	{
		"ControlName"	"Panel"
		"fieldName"		"ChalkBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
}

