"Resource/UI/HudDemomanPipes.res"
{
	"ChargeLabel"
	{
		"controlName"		"CExLabel"
		"fieldName"			"ChargeLabel"
		"xpos"				"cs-0.5"
		"ypos"				"c148"
		"zpos"				"0"
		"wide"				"48"
		"tall"				"16"
		"visible"			"1"	
		"labelText"			"#TF_Charge"
		"textAlignment"		"south"
		"allcaps"			"1"
		"font"				"HudMeterLabel"
		"fgColor_override"		"White"
		"bgColor_override"		"Black"
		"paintBackgroundType"	"2"
		"proportionalToParent"		"1"
	}

	"ChargeMeter"
	{
		"controlName"		"ContinuousProgressBar"
		"fieldName"			"ChargeMeter"
		"xpos"				"-5"
		"ypos"				"-2"
		"zpos"				"2"
		"wide"				"38"
		"tall"				"4"
		"visible"			"1"
		"enabled"			"1"
		"pin_to_sibling"	"ChargeLabel"
	}

	"MeterColor"
    {
        "controlName"		"ImagePanel"
        "fieldName"			"MeterColor"
		"xpos"				"0"
		"ypos"				"0"
        "zpos"				"3"
		"wide"				"38"
		"tall"				"4"
        "visible"			"1"
        "enabled"			"1"
        "image"				"replay/thumbnails/hud/modulate"
        "scaleImage"		"1"
        "drawColor"			"HudPrimary"
		"proportionalToParent"	"1"
		"pin_to_sibling"		"ChargeMeter"
    }

	"PipesPresentPanel"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"PipesPresentPanel"
		"xpos"			"cs-0.5"
		"ypos"			"c148"
		"zpos"			"4"
		"wide"			"48"
		"tall"			"16"
		"visible"		"1"	
		"bgColor_override"		"Black"
		"paintBackgroundType"	"2"

		"NumPipesLabel"
		{
			"controlName"				"CExLabel"
			"fieldName"					"NumPipesLabel"
			"xpos"						"rs1-6"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"30"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"%activepipes%"
			"textAlignment"				"east"
			"font"						"HudMeterCount"
			"fgColor"					"HudPrimary"
			"proportionalToParent"		"1"
		}
		"StickyIcon"
		{
			"controlName"				"CExLabel"
			"fieldName"					"StickyIcon"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"o1"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"4"
			"textinsetY"				"-0.8"
			"textAlignment"				"center"
			"font"						"HudInGameIcoSmall"
			"fgColor"					"HudPrimaryLight"
			"proportionalToParent"		"1"
			"use_proportional_insets"	"1"
		}

		"PipesIcon"
		{
			"fieldName"	"PipesIcon"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
		"NumPipesLabelDropshadow"
		{
			"fieldName"	"NumPipesLabelDropshadow"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
	}
	
	"NoPipesPresentPanel"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"NoPipesPresentPanel"
		"xpos"			"cs-0.5"
		"ypos"			"c148"
		"zpos"			"4"
		"wide"			"48"
		"tall"			"16"
		"visible"		"1"
		"bgColor_override"		"Black"
		"paintBackgroundType"	"2"

		"NumPipesLabel"
		{
			"controlName"				"CExLabel"
			"fieldName"					"NumPipesLabel"
			"xpos"						"rs1-6"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"30"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"%activepipes%"
			"textAlignment"				"east"
			"font"						"HudMeterCount"
			"fgColor"					"HudPrimary"
			"proportionalToParent"		"1"
		}		
		"StickyIcon"
		{
			"controlName"				"CExLabel"
			"fieldName"					"StickyIcon"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"o1"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"4"
			"textinsetY"				"-0.8"
			"textAlignment"				"center"
			"font"						"HudInGameIcoSmall"
			"fgColor"					"HudPrimaryLight"
			"proportionalToParent"		"1"
			"use_proportional_insets"	"1"
		}

		"PipesIcon"
		{
			"fieldName"	"PipesIcon"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
		"NumPipesLabelDropshadow"
		{
			"fieldName"	"NumPipesLabelDropshadow"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
	}				
}
