"Resource/UI/HudDamageAccount.res"
{
	"CDamageAccountPanel"
	{
		"fieldName"				"CDamageAccountPanel"
		"text_x"				"0"
		"text_y"				"0"
		"delta_item_end_y"		"0"
		"PositiveColor"			"20 250 20 255"
		"NegativeColor"			"255 165 0 255"
		"delta_lifetime"		"2"
		"delta_item_font"		"HudDamageOver"
		"delta_item_font_big"	"HudDamageOverLarge"
		"visible"				"1"
		"visible_minmode"		"1"
	}
	"DamageAccountValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c128"
		"ypos"			"rs1-118"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"36"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"east"
		"fgcolor"		"HudNegat"
		"font"			"HudMeterCountLarge"
	}	
	"DamageAccountValueShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValueShadow"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"36"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"east"
		"fgcolor"		"0 0 0 255"
		"font"			"HudMeterCountLarge"
		"pin_to_sibling"	"DamageAccountValue"
	}
}
