"Resource/UI/HudDemomanPipes.res"
{
	"ChargeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ChargeLabel"
		"xpos"				"cs-0.5+200"
		"ypos"				"rs1-58"
		"zpos"				"0"
		"wide"				"60"
		"tall"				"24"
		"visible"			"1"	
		"labelText"			"#TF_Charge"
		"textAlignment"		"south"
		"textinsety"		"-3"
		"allcaps"			"1"
		"font"				"HudMeterLabelLarge"
		"fgcolor_override"		"HudPrimaryLight"
		"bgcolor_override"		"Black"
		"paintBackgroundType"	"2"
		"proportionaltoparent"		"1"
		"use_proportional_insets"	"1"
	}

	"ChargeMeter"
	{
		"ControlName"		"ContinuousProgressBar"
		"fieldName"			"ChargeMeter"
		"xpos"				"-5"
		"ypos"				"-4"
		"zpos"				"2"
		"wide"				"50"
		"tall"				"5"
		"visible"			"1"
		"enabled"			"1"
		"pin_to_sibling"	"ChargeLabel"
	}

	"MeterColor"
    {
        "ControlName"		"ImagePanel"
        "fieldName"			"MeterColor"
		"xpos"				"0"
		"ypos"				"0"
        "zpos"				"3"
		"wide"				"50"
		"tall"				"5"
        "visible"			"1"
        "enabled"			"1"
        "image"				"replay/thumbnails/hud/modulate"
        "scaleImage"		"1"
        "drawcolor"			"HudPrimary"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"ChargeMeter"
    }

	"PipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"PipesPresentPanel"
		"xpos"			"cs-0.5+200"
		"ypos"			"rs1-58"
		"zpos"			"4"
		"wide"			"60"
		"tall"			"24"
		"visible"		"1"	
		"bgcolor_override"		"Black"
		"paintBackgroundType"	"2"

		"NumPipesLabel"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"NumPipesLabel"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"f0"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"%activepipes%"
			"textAlignment"				"east"
			"textinsetx"				"8"
			"font"						"HudMeterCountLarge"
			"fgcolor"					"HudPrimary"
			"proportionaltoparent"		"1"
			"use_proportional_insets"	"1"
		}
		"StickyIcon"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"StickyIcon"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"o1"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"4"
			"textAlignment"				"center"
			"font"						"HudInGameIco"
			"fgcolor"					"HudPrimaryLight"
			"fgcolor_override"			"HudPrimaryLight"
			"proportionaltoparent"		"1"
			"use_proportional_insets"	"1"
		}

		"PipesIcon"
		{
			"fieldName"	"PipesIcon"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
		"NumPipesLabelDropshadow"
		{
			"fieldName"	"NumPipesLabelDropshadow"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
	}
	
	"NoPipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"NoPipesPresentPanel"
		"xpos"			"cs-0.5+200"
		"ypos"			"rs1-58"
		"zpos"			"4"
		"wide"			"60"
		"tall"			"24"
		"visible"		"1"
		"bgcolor_override"		"Black"
		"paintBackgroundType"	"2"

		"NumPipesLabel"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"NumPipesLabel"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"f0"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"%activepipes%"
			"textAlignment"				"east"
			"textinsetx"				"8"
			"font"						"HudMeterCountLarge"
			"fgcolor"					"HudPrimary"
			"proportionaltoparent"		"1"
			"use_proportional_insets"	"1"
		}		
		"StickyIcon"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"StickyIcon"
			"xpos"						"0"
			"ypos"						"0"
			"zpos"						"2"
			"wide"						"o1"
			"tall"						"f0"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"4"
			"textAlignment"				"center"
			"font"						"HudInGameIco"
			"fgcolor"					"HudPrimaryLight"
			"proportionaltoparent"		"1"
			"use_proportional_insets"	"1"
		}

		"PipesIcon"
		{
			"fieldName"	"PipesIcon"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
		"NumPipesLabelDropshadow"
		{
			"fieldName"	"NumPipesLabelDropshadow"
			"xpos"		"9999"
			"wide"		"0"
			"visible"	"0"
		}
	}				
}
