"Resource/UI/HudMedicCharge.res"
{	
	"ChargeLabel"
	{
		"controlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"font"			"HudValue"
		"fgColor"		"HudPrimaryLight"
		"xpos"			"cs-0.5+184"
		"ypos"			"r127"
		"zpos"			"5"
		"wide"			"120"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"		
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"center"
	}

	"ChargeLabelShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow"
		"fgColor"		"Black"
		"font"			"HudValue"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"2"
		"wide"			"120"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"center"
		"pin_to_sibling"	"ChargeLabel"
	}

	"IndividualChargesLabel"
	{
		"controlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"cs-0.5+184"
		"ypos"			"r120"
		"zpos"			"3"
		"wide"			"105"
		"tall"			"34"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_IndividualUberchargesMinHUD"
		"textAlignment"	"east"
		"textinsetX"	"15"
		"fgColor"		"HudPrimaryLight"
		"bgColor_override"	"Black"
		"paintBackgroundType"	"2"
		"font"			"HudValueSmaller"
	}

	"ChargeMeter"
	{	
		"controlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"xpos"			"cs-0.5+185"
		"ypos"			"r80"
		"zpos"			"2"
		"wide"			"95"
		"tall"			"8"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgColor_override"	"HudPrimary"
		"bgColor_override"	"DarkerBlack"
	}		

	"ChargeBG"
	{
		"controlName"	"Panel"
		"fieldName"		"ChargeBG"
		"xpos"			"cs-0.5+185"
		"ypos"			"r84"
		"zpos"			"1"
		"wide"			"105"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"		
		"paintBackgroundType"	"2"
		"bgColor_override"	"Black"
	}

	"ChargeMeter1"
	{	
		"controlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"xpos"			"cs-0.5+147"
		"ypos"			"r80"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"8"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgColor_override"	"HudPrimary"
		"bgColor_override"	"DarkerBlack"
	}

	"ChargeMeter2"
	{	
		"controlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"8"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgColor_override"	"HudPrimary"
		"bgColor_override"	"DarkerBlack"
		"pin_to_sibling"	"ChargeMeter1"
		"pin_to_sibling_corner"	"1"
	}

	"ChargeMeter3"
	{	
		"controlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"8"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgColor_override"	"HudPrimary"
		"bgColor_override"	"DarkerBlack"
		"pin_to_sibling"	"ChargeMeter2"
		"pin_to_sibling_corner"	"1"
	}

	"ChargeMeter4"
	{	
		"controlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"8"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgColor_override"	"HudPrimary"
		"bgColor_override"	"DarkerBlack"
		"pin_to_sibling"	"ChargeMeter3"
		"pin_to_sibling_corner"	"1"
	}

	"ResistPin"
	{
		"controlName"		"Label"
		"fieldName"			"ResistPin"
		"xpos"				"cs-0.5+183"
		"ypos"				"r120"
		"zpos"				"0"
		"wide"				"100"
		"tall"				"0"
		"visible"			"1"
		"enabled"			"1"
		"bgColor_override"	"0 0 0 0"
	}

	"ResistIcon"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"wide"			"34"
		"tall"			"34"
		"zpos"			"3"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	

		"pin_to_sibling"			"ResistPin"
		"pin_corner_to_sibling"		"PIN_TOPLEFT"
		"pin_to_sibling_corner"		"0"
	}
}

