"Resource/UI/HudObjectiveTimePanel.res"
{	
	"TimePanelBG"
	{
		"ControlName"	"Panel"
		"fieldName"		"TimePanelBG"
		"xpos"			"cs-0.5"
		"ypos"			"7"
		"zpos"			"2"
		"wide"			"52"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"bgcolor_override"		"TransparentBlack"
		"paintBackgroundType"	"2"

		"proportionaltoparent"	"1"
		if_match
		{
			"visible"	"0"
		}
	}
	"TimePanelProgressBar"
	{
		"ControlName"			"CTFProgressBar"
		"fieldName"			"TimePanelProgressBar"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"WaitingForPlayersLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WaitingForPlayersLabel"
		"xpos"			"0"
		"ypos"			"25"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"textinsetx"	"6"
		"font"			"FontStoreOriginalPrice"
		"proportionaltoparent"	"1"
		"use_proportional_insets"	"1"
		"labelText"		"#game_WaitingForPlayers"
	}			
	"WaitingForPlayersBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"WaitingForPlayersBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"OvertimeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"OvertimeLabel"
		"xpos"			"0"
		"ypos"			"25"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"20"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"
		"textinsetx"	"6"
		"font"			"FontStorePrice"
		"proportionaltoparent"	"1"
		"use_proportional_insets"	"1"
		"labelText"		"#game_Overtime"
	}			
	"OvertimeBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"OvertimeBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"SuddenDeathLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"SuddenDeathLabel"
		"xpos"			"0"
		"ypos"			"25"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"textinsetx"	"6"
		"font"			"FontStorePrice"
		"proportionaltoparent"	"1"
		"use_proportional_insets"	"1"
		"labelText"		"#game_SuddenDeath"
	}			
	"SuddenDeathBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"SuddenDeathBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}	
	"SetupLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SetupLabel"
		"xpos"			"0"
		"ypos"			"25"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"textinsetx"	"6"
		"font"			"FontStoreOriginalPrice"
		"proportionaltoparent"	"1"
		"use_proportional_insets"	"1"
		"labelText"		"#game_Setup"
	}	
	"SetupBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"SetupBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"ServerTimeLimitLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ServerTimeLimitLabel"
		"xpos"			"0"
		"ypos"			"35"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"textinsetx"	"6"
		"font"			"FontStorePrice"
		"proportionaltoparent"	"1"
		"use_proportional_insets"	"1"
		"labelText"		"%servertimeleft%"
	}	
	"ServerTimeLimitLabelBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"ServerTimeLimitLabelBG"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"	
	}
}
