"Resource/UI/MainMenuPlayListEntry.res"
{
	"ModeImage"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"ModeImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"o4"
		"tall"			"p1.17"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"proportionalToParent"	"1"
		"image"			""
	}

	"PlayListDropShadow"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"PlayListDropShadow"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1000"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"1"
		"paintBackgroundType"	"2"
		"border"		"InnerShadowBorderThin"
		"proportionalToParent"	"1"
		"mouseInputEnabled"	"0"
	}

	"bgColor"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"bgColor"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"1"
		"enabled"		"1"
		
		"proportionalToParent"	"1"
		"bgColor_override"	"0 0 0 255"
	}

	
	"ToolTipHack"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"ToolTipHack"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"50"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"0"
		"enabled"		"1"
		"mouseInputEnabled"	"1"
		"eatmouseinput"	"0"	
		"showtooltipswhenmousedisabled"	"1"
	}

	"ToolTipButtonHack"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"ToolTipButtonHack"
		"xpos"			"rs1-6"
		"ypos"			"2"
		"zpos"			"51"
		"wide"			"122"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"mouseInputEnabled"	"1"
		"eatmouseinput"	"0"	
		"showtooltipswhenmousedisabled"	"1"
		"proportionalToParent" "1"
	}

	"ModeButton"
	{
		"controlName"	"CExButton"
		"fieldName"		"ModeButton"
		"xpos"			"rs1-8"
		"ypos"			"cs-0.5"
		"zpos"			"6"
		"wide"			"122"
		"tall"			"f12"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%button_token%"
		"textinsetX"	"4"
		"use_proportional_insets" "1"
		"font"			"HudFontSmallestBold"
		"textAlignment"	"west"
		"default"		"1"
		"command"		"%button_command%"
		"proportionalToParent" "1"
		"actionSignalLevel"	"2"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	

	"MatchmakingBanPanel"
	{
		"controlName"	"EditablePanel"
		"fieldName"		"MatchmakingBanPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"0"
		"enabled"		"1"
		"mouseInputEnabled"	"0"
		"bgColor_override"	"0 0 0 250"
		"proportionalToParent"	"1"

		"MatchmakingBanDurationLabel"
		{
			"controlName"	"CExLabel"
			"fieldName"		"MatchmakingBanDurationLabel"
			"font"			"MMenuPlayListDesc"
			"fgColor_override"	"RedSolid"
			"labelText"		"#TF_Matchmaking_Ban_Duration_Remaining"
			"textAlignment"	"south-west"
			"xpos"			"5"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"f0"
			"tall"			"f0"
			"visible"		"1"
			"enabled"		"1"
			"autoResize"	"1"
			"pinCorner"		"0"
			"proportionalToParent"	"1"

			"paintBackground"	"0"
		}
	}

	"DescLabel"
	{
		"controlName"	"CExLabel"
		"fieldName"		"DescLabel"
		"font"			"MMenuPlayListDesc"
		"labelText"		"%desc_token%"
		"textAlignment"	"north-west"
		"xpos"			"rs1"
		"ypos"			"18"
		"zpos"			"2"
		"wide"			"125"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
		"fgColor_override" "TanLight"
		"proportionalToParent" "1"
		"mouseInputEnabled"	"0"
	}

	"DescLabelShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"DescLabelShadow"
		"font"			"MMenuPlayListDesc"
		"labelText"		"%desc_token%"
		"textAlignment"	"north-west"
		"xpos"			"rs1+1"
		"ypos"			"19"
		"zpos"			"1"
		"wide"			"125"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
		"fgColor_override" "Black"
		"proportionalToParent" "1"
		"mouseInputEnabled"	"0"
	}
	
	"DisabledIcon"
	{
		"controlName"	"CExImageButton"
		"fieldName"		"DisabledIcon"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"				"49"
		"wide"				"f0"
		"tall"				"f0"
		"visible"			"0"
		"enabled"			"1"
		"actionSignalLevel"	"1"
		"command"			"comp_access_info"
		"labelText"			""
		"eatmouseinput"	"0"	
		"button_activation_type"	"1"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
				
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "235 226 202 255"
		"depressedFgColor_override" "46 43 42 255"
		"defaultBgColor_override" "0 0 0 0"
		"armedBgColor_override" "0 0 0 0"
		"depressedbgColor_override" "0 0 0 0"
				
		"image_drawColor"	"235 226 202 255"
		"image_armedColor"	"235 140 140 255"
		"SubImage"
		{
			"controlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"233"
			"ypos"			"2"
			"zpos"			"1"
			"wide"			"15"
			"tall"			"15"
			"visible"		"1"
			"enabled"		"1"
			"image"			"locked_icon"
			"scaleImage"	"1"
			"proportionalToParent" "1"
		}	
	}
}