"Resource/UI/winpanel.res"
{
	"TFStatsSummary"
	{
		"controlName"	"EditablePanel"
		"fieldName"	"TFStatsSummary"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"f0"
		"visible"	"0"
		"enabled"	"1"
		"bgColor_override"	"DarkBlack"
	}	
	"MainBackground"
	{
		"controlName"		"ImagePanel"
		"fieldName"		"MainBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"0"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"
	}				
	"StatData"
	{
		"controlName"	"EditablePanel"
		"fieldName"	"StatData"
		"xpos"		"cs-0.5"
		"ypos"		"-130"
		"zpos"		"1"
		"wide"		"590"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"

		"NonInteractiveHeaders"
		{
			"controlName"	"EditablePanel"
			"fieldName"	"NonInteractiveHeaders"
			"xpos"		"0"
			"ypos"		"0"
			"zpos"		"2"
			"wide"		"f0"
			"tall"		"480"
			"visible"	"1"
			"enabled"	"1"
	
			"BarChartLabelA"
			{
				"controlName"		"Label"
				"fieldName"		"BarChartLabelA"
				"font"			"ScoreboardSmallOutline"
				"labelText"		"#StatSummary_StatTitle_MostPoints"
				"textAlignment"		"east"
				"xpos"			"5"
				"ypos"			"206"
				"zpos"			"5"
				"wide"			"151"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
			}
			"BarChartLabelB"
			{
				"controlName"		"Label"
				"fieldName"		"BarChartLabelB"
				"font"			"ScoreboardSmallOutline"
				"labelText"		"#StatSummary_StatTitle_TotalPlaytime"
				"textAlignment"		"west"
				"xpos"			"8"
				"ypos"			"0"
				"zpos"			"5"
				"wide"			"151"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"pin_to_sibling"	"BarChartLabelA"
				"pin_to_sibling_corner"	"PIN_TOPRIGHT"
			}			
			"OverallRecordLabel"
			{
				"controlName"		"Label"
				"fieldName"		"OverallRecordLabel"
				"font"			"ScoreboardSmallOutline"
				"labelText"		"#StatSummary_Label_AsAnyClass"
				"textAlignment"		"west"
				"xpos"			"415"
				"ypos"			"206"
				"zpos"			"5"
				"wide"			"155"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
			}				
		}
		"InteractiveHeaders"	
		{
			"controlName"	"EditablePanel"
			"fieldName"	"InteractiveHeaders"
			"xpos"		"0"
			"ypos"		"0"
			"zpos"		"2"
			"wide"		"f0"
			"tall"		"480"
			"visible"	"1"
			"enabled"	"1"

			"BarChartComboA"
			{
				"controlName"	"ComboBox"
				"fieldName"		"BarChartComboA"
				"xpos"			"5"
				"ypos"			"212"
				"zpos"			"10"
				"wide"			"154"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"textHidden"	"0"
				"editable"		"0"
				"maxchars"		"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
			}
			"BarChartComboB"
			{
				"controlName"	"ComboBox"
				"fieldName"		"BarChartComboB"
				"xpos"			"5"
				"ypos"			"0"
				"zpos"			"10"
				"wide"			"154"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"textHidden"	"0"
				"editable"		"0"
				"maxchars"		"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				"pin_to_sibling"	"BarChartComboA"
				"pin_to_sibling_corner"	"PIN_TOPRIGHT"
			}
			"ClassCombo"
			{
				"controlName"	"ComboBox"
				"fieldName"		"ClassCombo"
				"xpos"			"415"
				"ypos"			"212"
				"zpos"			"10"
				"wide"			"167"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"textHidden"	"0"
				"editable"		"0"
				"maxchars"		"-1"
				"NumericInputOnly"		"0"
				"unicode"		"0"
			}
		}
		"AveragesBG"
		{
			"controlName"	"EditablePanel"
			"fieldName"		"AveragesBG"
			"xpos"			"0"
			"ypos"			"200"
			"wide"			"402"
			"tall"			"205"
			"visible"		"1"
			"enabled"		"1"
			"bgColor_override"	"TransparentBlack"
			"paintBackgroundType"	"2"
		}
		"AveragesLabel"
		{
			"controlName"	"Label"
			"fieldName"		"AveragesLabel"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"#StatSummary_Label_PerformanceReport"
			"textAlignment"	"west"
			"xpos"			"0"
			"ypos"			"160"
			"wide"			"338"
			"tall"			"35"
			"visible"		"1"
			"enabled"		"1"
			"bgColor_override"	"TransparentBlack"
			"paintBackgroundType"	"2"
			"roundedCorners"		"5"

			"textinsetX"		"15"
			"use_proportional_insets"	"1"
		}
		"ClassBarBG1A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG1A"
			"xpos"			"5"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}	
		"ClassBarBG1B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG1B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG1A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar1A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar1A"
			"xpos"			"8"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}
		"ClassBar1B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar1B"
			"xpos"			"163"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel1A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel1A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel1A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel1B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel1B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel1B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel1"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel1"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class1%"
			"textAlignment"	"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG1B"
		}				
		"ClassBarBG2A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG2A"
			"xpos"			"5"
			"ypos"			"248"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG2B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG2B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG2A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar2A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar2A"
			"xpos"			"c-282"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}	
		"ClassBar2B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar2B"
			"xpos"			"c-127"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel2A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel2A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel2A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel2B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel2B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel2B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel2"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel2"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class2%"
			"textAlignment"	"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG2B"
		}				
		"ClassBarBG3A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG3A"
			"xpos"			"5"
			"ypos"			"266"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG3B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG3B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG3A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar3A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar3A"
			"xpos"			"c-282"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}	
		"ClassBar3B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar3B"
			"xpos"			"c-127"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryDark"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel3A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel3A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel3A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel3B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel3B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel3B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel3"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel3"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class3%"
			"textAlignment"	"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG3B"
		}				
		"ClassBarBG4A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG4A"
			"xpos"			"5"
			"ypos"			"284"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG4B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG4B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG4A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar4A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar4A"
			"xpos"			"c-282"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBar4B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar4B"
			"xpos"			"c-127"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel4A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel4A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel4A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel4B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel4B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel4B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel4"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel4"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class4%"
			"textAlignment"	"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG4B"
		}				
		"ClassBarBG5A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG5A"
			"xpos"			"5"
			"ypos"			"302"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG5B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG5B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG5A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar5A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar5A"
			"xpos"			"c-282"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBar5B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar5B"
			"xpos"			"c-127"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel5A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel5A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel5A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel5B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel5B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel5B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel5"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel5"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class5%"
			"textAlignment"		"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG5B"
		}				
		"ClassBarBG6A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG6A"
			"xpos"			"5"
			"ypos"			"320"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG6B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG6B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG6A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar6A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar6A"
			"xpos"			"c-282"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBar6B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar6B"
			"xpos"			"c-127"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimary"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel6A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel6A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel6A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel6B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel6B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel6B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel6"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel6"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class6%"
			"textAlignment"		"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG6B"
		}				
		"ClassBarBG7A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG7A"
			"xpos"			"5"
			"ypos"			"338"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG7B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG7B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG7A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar7A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar7A"
			"xpos"			"c-282"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBar7B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar7B"
			"xpos"			"c-127"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel7A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel7A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel7A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel7B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel7B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel7B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel7"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel7"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class7%"
			"textAlignment"		"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG7B"
		}		
		"ClassBarBG8A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG8A"
			"xpos"			"5"
			"ypos"			"356"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG8B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG8B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG8A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar8A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar8A"
			"xpos"			"c-282"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBar8B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar8B"
			"xpos"			"c-127"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel8A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel8A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel8A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"354"

			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel8B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel8B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel8B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"354"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel8"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel8"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class8%"
			"textAlignment"		"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG8B"
		}		
		"ClassBarBG9A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG9A"
			"xpos"			"5"
			"ypos"			"374"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
		}
		"ClassBarBG9B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBarBG9B"
			"xpos"			"8"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"pin_to_sibling"		"ClassBarBG9A"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		}
		"ClassBar9A"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar9A"
			"xpos"			"c-282"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBar9B"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"ClassBar9B"
			"xpos"			"c-127"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"HudPrimaryLight"
			"paintBackgroundType"	"0"
		}	
		"ClassBarLabel9A"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel9A"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel9A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel9B"
		{
			"controlName"		"Label"
			"fieldName"		"ClassBarLabel9B"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classbarlabel9B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel9"
		{
			"controlName"		"Label"
			"fieldName"		"ClassLabel9"
			"font"			"ScoreboardSmallOutline"
			"labelText"		"%class9%"
			"textAlignment"		"west"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"textinsetX"	"5"
			"use_proportional_insets"	"1"
			"fgColor_override"	"White"
			"pin_to_sibling"		"ClassBarBG9B"
		}		
		"RecordsBG"
		{
			"controlName"		"EditablePanel"
			"fieldName"		"RecordsBG"
			"xpos"			"rs1"
			"ypos"			"200"
			"wide"			"182"
			"tall"			"240"
			"visible"		"1"
			"enabled"		"1"
			"paintBackgroundType"	"2"
			"bgColor_override"	"TransparentBlack"
			"roundedCorners"	"15"
			"proportionalToParent"	"1"
		}
		"RecordsLabel1"
		{
			"controlName"	"Label"
			"fieldName"		"RecordsLabel1"
			"font"			"HudFontSmallBold"
			"labelText"		"#StatSummary_Label_BestMoments"
			"xpos"			"rs1"
			"ypos"			"160"
			"wide"			"252"
			"tall"			"35"
			"visible"		"1"
			"enabled"		"1"
			"textAlignment"	"east"
			"paintBackgroundType"	"2"
			"bgColor_override"	"TransparentBlack"
			"roundedCorners"	"10"
			"proportionalToParent"	"1"

			"textinsetX"		"20"
			"use_proportional_insets"	"1"
		}							
		"RecordsSubBG1"
		{
			"controlName"		"ImagePanel"
			"fieldName"		"RecordsSubBG1"
			"xpos"			"rs1-8"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"167"
			"tall"			"200"
			"visible"		"1"
			"enabled"		"1"
			"fillColor"		"Black"
			"paintBackgroundType"	"0"
			"proportionalToParent"	"1"
		}
		"OverallRecord1Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord1Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord1label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"228"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord1Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord1Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord1value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"228"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord2Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord2label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"241"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord2Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord2value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"241"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord3Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord3label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"254"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord3Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord3value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"254"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord4Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord4label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"267"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord4Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord4value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"267"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord5Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord5label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"280"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord5Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord5value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"280"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord6Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord6label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"293"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord6Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord6value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"293"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord7Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord7label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"306"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord7Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord7value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"306"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord8Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord8label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"319"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord8Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord8value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"319"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord9Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord9Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord9label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"332"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord9Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord9Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord9value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"332"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord10Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord10Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord10label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"345"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord10Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord10Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord10value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"345"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord11Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord11Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord11label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"358"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord11Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord11Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord11value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"358"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord12Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord12Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord12label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"371"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord12Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord12Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord12value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"371"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord13Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord13Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord13label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"384"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord13Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord13Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord13value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"384"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord14Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord14Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord14label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"397"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord14Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord14Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord14value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"397"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord15Label"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord15Label"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord15label%"
			"textAlignment"		"west"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"410"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord15Value"
		{
			"controlName"		"Label"
			"fieldName"		"OverallRecord15Value"
			"font"			"ScoreboardVerySmallOutline"
			"labelText"		"%classrecord15value%"
			"textAlignment"		"east"
			"proportionalToParent"	"1"
			"xpos"			"rs1-14"
			"ypos"			"410"
			"zpos"			"5"
			"wide"			"155"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
	}

	"TipBG"
	{
		"controlName"		"EditablePanel"
		"fieldName"		"TipBG"
		"xpos"			"c-295"
		"ypos"			"280"
		"wide"			"402"
		"tall"			"56"
		"visible"		"1"
		"enabled"		"1"
		"bgColor_override"	"TransparentBlack"
		"paintBackgroundType"	"2"
	}

	"TipImage"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"TipImage"
		"xpos"			"c-285"
		"ypos"			"290"
		"zpos"			"12"
		"wide"			"35"
		"tall"			"35"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleImage"	"1"	
	}
	"TipText"
	{
		"controlName"	"Label"
		"fieldName"		"TipText"
		"font"			"ScoreboardVerySmallOutline"
		"labelText"		"%tiptext%"
		"xpos"			"30"
		"ypos"			"283"
		"zpos"			"12"
		"wide"			"340"
		"tall"			"48"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
	}
	"NextTipButton"
	{
		"controlName"	"Button"
		"fieldName"		"NextTipButton"
		"xpos"			"c113"
		"ypos"			"319"
		"zpos"			"6"
		"wide"			"90"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_NextTip"
		"textAlignment"	"center"
		"command"		"nexttip"

		"defaultBgColor_override"	"TransparentBlack"
	}

	"ResetStatsButton"
	{
		"controlName"	"Button"
		"fieldName"		"ResetStatsButton"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"CloseButton"
	{
		"controlName"	"Button"
		"fieldName"		"CloseButton"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
}
