#base "../../../../cfg/rosehud/hud_shaders_tx.txt"

#base "../../_base/textpanel_base.res"

"Resource/UI/TeamMenu.res"
{
	"team"
	{
		"controlName"	"CTeamMenu"
		"fieldName"		"team"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}

	"SysMenu"
	{
		"controlName"	"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"64"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"MapInfo"
	{
		"controlName"	"HTML"
		"fieldName"		"MapInfo"
		"xpos"			"100"
		"ypos"			"34"
		"wide"			"450"
		"tall"			"365"
		"autoResize"	"3"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"mapname"
	{
		"controlName"	"Label"
		"fieldName"		"mapname"
		"xpos"			"c-310"
		"ypos"			"50"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"west"
	}
	
	"teambutton0"
	{
		"controlName"	"CTFTeamButton"
		"fieldName"		"teambutton0"
		"xpos"			"cs0"
		"ypos"			"160"
		"wide"			"220"
		"tall"			"60"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"BLU (&2)"
		"textAlignment"	"center"
		"command"		"jointeam blue"
		"font"			"HudFontMediumBigBold"
		"paintBackgroundType"		"2"
		"roundedCorners"			"10"
		"use_proportional_insets"	"1"
		"proportionalToParent"		"1"
		"defaultBgColor_override"	"BlueTeamSolid"
		"armedBgColor_override"		"LightBlueTeamSolid"
		"depressedBgColor_override"	"DarkBlueTeamSolid"

		"depressedFgColor_override"	"Black"
	}

	"teambutton1"
	{
		"controlName"	"CTFTeamButton"
		"fieldName"		"teambutton1"
		"xpos"			"cs-1"
		"ypos"			"160"
		"zpos"			"1"
		"wide"			"220"
		"tall"			"60"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"RED (&1)"
		"textAlignment"	"center"
		"command"		"jointeam red"
		"font"			"HudFontMediumBigBold"
		"paintBackgroundType"		"2"
		"roundedCorners"			"5"
		"use_proportional_insets"	"1"
		"proportionalToParent"		"1"
		"defaultBgColor_override"	"RedTeamSolid"
		"armedBgColor_override"		"LightRedTeamSolid"
		"depressedBgColor_override"	"DarkRedTeamSolid"

		"depressedFgColor_override"	"Black"
	}

	"teambutton2"
	{
		"controlName"	"CExButton"
		"fieldName"		"teambutton2"
		"xpos"			"cs-1.1"
		"ypos"			"292"
		"wide"			"180"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Random"
		"textAlignment"	"center"
		"command"		"jointeam auto"
		"font"			"HudFontMediumBold"

		"defaultFgColor_override" 	"White"
		"armedFgColor_override"		"Black"
		"depressedFgColor_override" "HudPrimaryLight"
	}
	
	"teambutton3"
	{
		"controlName"	"CExButton"
		"fieldName"		"teambutton3"
		"xpos"			"cs0.1"
		"ypos"			"292"
		"wide"			"180"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Spectate"
		"textAlignment"	"center"
		"command"		"jointeam spectate"
		"font"			"HudFontMediumBold"

		"defaultFgColor_override" 	"White"
		"armedFgColor_override"		"Black"
		"depressedFgColor_override" "HudPrimaryLight"
	}

	"CancelButton"
	{
		"controlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"			"0"
		"ypos"			"rs1"
		"zpos"			"6"
		"wide"			"f0"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#rose_Cancel"
		"textAlignment"	"center"
		"command"		"cancelmenu"
		"font"			"HudFontSmallBold"
		"roundedCorners"	"0"
		"defaultBgColor_override"	"DarkerBlack"
	}
	
	"TeamMenuSelect"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamMenuSelect"
		"xpos"			"0"
		"ypos"			"50"
		"zpos"			"6"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_SelectATeam"
		"textAlignment"	"center"
		"font"			"HudFontBiggerBold"
	}

	"TeamMenuRed"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamMenuRed"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"TeamMenuBlue"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamMenuBlue"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"TeamMenuAuto"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamMenuAuto"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"TeamMenuSpectate"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamMenuSpectate"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"BlueCountBG"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"BlueCountBG"
		"xpos"			"c18"
		"ypos"			"c5"
		"zpos"			"-2"
		"wide"			"58"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"fillColor" 	"BlueTeamTransparent"
	}

	"BlueCountBG2"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"BlueCountBG2"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"-1"
		"wide"			"54"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"fillColor" 	"BlueTeamSolid"
		"pin_to_sibling"	"BlueCountBG"
	}

	"BlueCount"
	{
		"controlName"	"CExLabel"
		"fieldName"		"BlueCount"
		"xpos"			"-13"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"41"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%bluecount%"
		"textAlignment"	"center"
		"font"			"HudFontSmallishBold"
		"fgColor"		"White"
		"pin_to_sibling"	"BlueCountBg2"
	}	

	"BlueCountImage"
	{
		"controlName"	"CExLabel"
		"fieldName"		"BlueCountImage"
		"xpos"			"-2"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"15"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"P"
		"textAlignment"	"center"
		"font"			"HudMenuIco"
		"fgColor"		"White"
		"pin_to_sibling"	"BlueCountBg2"
	}	

	"RedCountBG"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"RedCountBG"
		"xpos"			"c-76"
		"ypos"			"c5"
		"zpos"			"-2"
		"wide"			"58"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"fillColor" 	"RedTeamTransparent"
	}

	"RedCountBG2"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"RedCountBG2"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"-1"
		"wide"			"54"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"fillColor" 	"RedTeamSolid"
		"pin_to_sibling"	"RedCountBG"
	}

	"RedCount"
	{
		"controlName"	"CExLabel"
		"fieldName"		"RedCount"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"41"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%redcount%"
		"textAlignment"	"center"
		"font"			"HudFontSmallishBold"
		"fgColor"		"White"
		"pin_to_sibling"	"RedCountBg2"
	}	

	"RedCountImage"
	{
		"controlName"	"CExLabel"
		"fieldName"		"RedCountImage"
		"xpos"			"-2"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"15"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"P"
		"textAlignment"	"center"
		"font"			"HudMenuIco"
		"fgColor"		"White"
		"pin_to_sibling"	"RedCountBg2"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
	}	
	
	"HighlanderLabel"
	{
		"controlName"	"CExLabel"
		"fieldName"		"HighlanderLabel"
		"xpos"			"c-150"
		"ypos"			"100"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Highlander_Mode"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgColor"		"HudOffWhite"
		"centerWrap"	"1"
	}
	
	"HighlanderLabelShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"HighlanderLabelShadow"
		"xpos"			"c-149"
		"ypos"			"101"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Highlander_Mode"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgColor"		"black"
		"centerWrap"	"1"
	}
	
	"TeamsFullLabel"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamsFullLabel"
		"xpos"			"c-150"
		"ypos"			"135"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Teams_Full"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgColor"		"HudOffWhite"
		"centerWrap"	"1"
	}
	
	"TeamsFullLabelShadow"
	{
		"controlName"	"CExLabel"
		"fieldName"		"TeamsFullLabelShadow"
		"xpos"			"c-149"
		"ypos"			"136"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Teams_Full"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgColor"		"black"
		"centerWrap"	"1"
	}

	"TeamsFullArrow"
	{
		"controlName"	"CTFImagePanel"
		"fieldName"		"TeamsFullArrow"
		"xpos"			"c-118"
		"ypos"			"165"
		"zpos"			"6"
		"wide"			"40"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../HUD/arrow_big_down"
		"scaleImage"	"1"	
	}

	"BGDarken"
	{
		"xpos"		"9999"
		"wide"		"0"
		"visible"	"0"
	}
	
	"ChalkBG"
	{
		"xpos"		"9999"
		"wide"		"0"
		"visible"	"0"
	}
}

