#base "textpanel_base.res"
"Resource/UI/TeamMenu.res"
{
	"team"
	{
		"ControlName"	"CTeamMenu"
		"fieldName"		"team"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}

	"SysMenu"
	{
		"ControlName"	"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"64"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"MapInfo"
	{
		"ControlName"	"HTML"
		"fieldName"		"MapInfo"
		"xpos"			"100"
		"ypos"			"34"
		"wide"			"450"
		"tall"			"365"
		"autoResize"	"3"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"mapname"
	{
		"ControlName"	"Label"
		"fieldName"		"mapname"
		"xpos"			"c-310"
		"ypos"			"50"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"west"
	}
	
	"teambutton0"
	{
		"ControlName"	"CTFTeamButton"
		"fieldName"		"teambutton0"
		"xpos"			"cs0"
		"ypos"			"140"
		"wide"			"220"
		"tall"			"60"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"BLU (&2)"
		"textAlignment"	"center"
		"command"		"jointeam blue"
		"font"			"HudFontMediumBigBold"
		"paintBackgroundType"		"2"
		"bgcolor_override"			"BlueTeamSolid"
		"roundedcorners"			"10"
		"use_proportional_insets"	"1"
		"proportionaltoparent"		"1"
	}

	"teambutton1"
	{
		"ControlName"	"CTFTeamButton"
		"fieldName"		"teambutton1"
		"xpos"			"cs-1"
		"ypos"			"140"
		"zpos"			"1"
		"wide"			"220"
		"tall"			"60"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"RED (&1)"
		"textAlignment"	"center"
		"command"		"jointeam red"
		"font"			"HudFontMediumBigBold"
		"paintBackgroundType"		"2"
		"bgcolor_override"			"RedTeamSolid"
		"roundedcorners"			"5"
		"use_proportional_insets"	"1"
		"proportionaltoparent"		"1"
	}

	"teambutton2"
	{
		"ControlName"	"CExButton"
		"fieldName"		"teambutton2"
		"xpos"			"cs-1.1"
		"ypos"			"300"
		"wide"			"80"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&3"
		"textAlignment"	"center"
		"command"		"jointeam auto"
		"font"			"HudFontMediumBold"

		"defaultbgcolor_override" 	"Black"
		"armedbgcolor_override"		"HudPrimary"
		"depressedbgcolor_override" "HudPrimaryDark"

		"defaultfgcolor_override" 	"White"
		"armedfgcolor_override"		"Black"
		"depressedfgcolor_override" "HudPrimaryLight"
	}
	
	"teambutton3"
	{
		"ControlName"	"CExButton"
		"fieldName"		"teambutton3"
		"xpos"			"cs0.1"
		"ypos"			"300"
		"wide"			"80"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&4"
		"textAlignment"	"center"
		"command"		"jointeam spectate"
		"font"			"HudFontMediumBold"
		
		"defaultbgcolor_override" 	"Black"
		"armedbgcolor_override"		"HudPrimary"
		"depressedbgcolor_override" "HudPrimaryDark"

		"defaultfgcolor_override" 	"White"
		"armedfgcolor_override"		"Black"
		"depressedfgcolor_override" "HudPrimaryLight"
	}

	"CancelButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"			"0"
		"ypos"			"rs1"
		"zpos"			"6"
		"wide"			"f0"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#rose_Cancel"
		"textAlignment"	"center"
		"command"		"cancelmenu"
		"font"			"HudFontSmallBold"
		"roundedcorners"	"0"
	}
	
	"TeamMenuSelect"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuSelect"
		"xpos"			"0"
		"ypos"			"50"
		"zpos"			"6"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_SelectATeam"
		"textAlignment"	"center"
		"font"			"HudFontBiggerBold"
	}

	"TeamMenuRed"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuRed"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"TeamMenuRedShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuRedShadow"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"TeamMenuBlue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuBlue"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"TeamMenuBlueShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuBlueShadow"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	
	"TeamMenuAuto"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuAuto"
		"xpos"			"cs-1.1"
		"ypos"			"275"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Random"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontSmallBold"
		"fgcolor"		"White"
	}

	"TeamMenuAutoShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuAutoShadow"
		"xpos"			"cs-1.1+1"
		"ypos"			"276"
		"wide"			"80"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Random"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontSmallBold"
		"fgcolor"		"Black"
	}
	
	"TeamMenuSpectate"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuSpectate"
		"xpos"			"cs0.1"
		"ypos"			"275"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Spectate"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontSmallBold"
		"fgcolor"		"white"
	}

	"TeamMenuSpectateShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamMenuSpectateShadow"
		"xpos"			"cs0.1+1"
		"ypos"			"276"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Spectate"
		"textAlignment"	"center"
		"wrap"			"0"
		"font"			"HudFontSmallBold"
		"fgcolor"		"black"
	}
	
	"BlueCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueCount"
		"xpos"			"c28"
		"ypos"			"248"
		"zpos"			"1"
		"wide"			"40"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%bluecount%"
		"textAlignment"	"center"
		"font"			"HudFontSmallishBold"
		"fgcolor"		"White"
	}

	"BlueCountBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BlueCountBG"
		"xpos"			"c28"
		"ypos"			"248"
		"zpos"			"-1"
		"wide"			"40"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor" 	"BlueTeamSolid"
	}

	"BlueCountBG2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BlueCountBG2"
		"xpos"			"c26"
		"ypos"			"246"
		"zpos"			"-2"
		"wide"			"44"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor" 	"BlueTeamTransparent"
	}
	
	"RedCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedCount"
		"xpos"			"c-68"
		"ypos"			"248"
		"zpos"			"1"
		"wide"			"40"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%redcount%"
		"textAlignment"	"center"
		"font"			"HudFontSmallishBold"
		"fgcolor"		"White"
	}	

	"RedCountBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"RedCountBG"
		"xpos"			"c-68"
		"ypos"			"248"
		"zpos"			"-1"
		"wide"			"40"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor" 	"RedTeamSolid"
	}

	"RedCountBG2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"RedCountBG2"
		"xpos"			"c-70"
		"ypos"			"246"
		"zpos"			"-2"
		"wide"			"44"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor" 	"RedTeamTransparent"
	}
	
	"HighlanderLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HighlanderLabel"
		"xpos"			"c-150"
		"ypos"			"100"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Highlander_Mode"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgcolor"		"HudOffWhite"
		"centerwrap"	"1"
	}
	
	"HighlanderLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HighlanderLabelShadow"
		"xpos"			"c-149"
		"ypos"			"101"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Highlander_Mode"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgcolor"		"black"
		"centerwrap"	"1"
	}
	
	"TeamsFullLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamsFullLabel"
		"xpos"			"c-150"
		"ypos"			"135"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Teams_Full"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgcolor"		"HudOffWhite"
		"centerwrap"	"1"
	}
	
	"TeamsFullLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TeamsFullLabelShadow"
		"xpos"			"c-149"
		"ypos"			"136"
		"zpos"			"6"
		"wide"			"105"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Teams_Full"
		"textAlignment"	"west"
		"font"			"CapPlayerFont"
		"fgcolor"		"black"
		"centerwrap"	"1"
	}

	"TeamsFullArrow"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"TeamsFullArrow"
		"xpos"			"c-118"
		"ypos"			"165"
		"zpos"			"6"
		"wide"			"40"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../HUD/arrow_big_down"
		"scaleImage"	"1"	
	}

	"BGDarken"
	{
		"xpos"		"9999"
		"wide"		"0"
		"visible"	"0"
	}
	"ChalkBG"
	{
		"xpos"		"9999"
		"wide"		"0"
		"visible"	"0"
	}
}

