"Resource/UI/winpanel.res"
{
	"TeamScoresPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"TeamScoresPanel"
		"xpos"			"0"
		"ypos"			"45"
		"wide"			"220"
		"tall"			"100"
		"visible"		"1"

		"BlueScoreBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"BlueScoreBG"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}
		"RedScoreBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"RedScoreBG"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}
		"BlueTeamLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"BlueTeamLabel"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}			
		"BlueTeamLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"BlueTeamLabelShadow"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}							
		"BlueTeamScore"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%blueteamscore%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"110"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"		"BlueTeamTransparent"
			"paintBackgroundType"	"2"
			"roundedcorners"		"5"
		}
		"BlueTeamScoreDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScoreDropshadow"
			"font"			"HudFontGiantBold"
			"labelText"		"%blueteamscore%"
			"textAlignment"	"center"
			"xpos"			"-2"
			"ypos"			"-2"
			"zpos"			"0"
			"wide"			"110"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"Black"
			"pin_to_sibling"	"BlueTeamScore"
		}
		"BlueLeaderAvatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"BlueLeaderAvatar"
			"xpos"			"61"
			"ypos"			"14"
			"zpos"			"5"
			"wide"			"40"
			"tall"			"40"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleImage"	"1"	
			"color_outline"	"52 48 45 255"
		}
		"BlueLeaderAvatarBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"BlueLeaderAvatarBG"
			"xpos"			"59"
			"ypos"			"12"
			"zpos"			"4"
			"wide"			"44"
			"tall"			"44"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"bgcolor_override"	"117 107 94 255"
		}									
		"RedTeamLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabel"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}

		"RedTeamLabelShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RedTeamLabelShadow"
			"xpos"			"9999"
			"wide"			"0"
			"visible"		"0"
		}		

		"RedTeamScore"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%redteamscore%"
			"textAlignment"	"center"
			"xpos"			"rs1"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"110"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"proportionaltoparent"	"1"
			"bgcolor_override"		"RedTeamTransparent"
			"paintBackgroundType"	"2"
			"roundedcorners"		"10"
		}
		"RedTeamScoreDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScoreDropshadow"
			"font"			"HudFontGiantBold"
			"labelText"		"%redteamscore%"
			"textAlignment"	"center"
			"xpos"			"-2"
			"ypos"			"-2"
			"zpos"			"0"
			"wide"			"110"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"Black"
			"pin_to_sibling"	"RedTeamScore"
		}
		"RedLeaderAvatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"RedLeaderAvatar"
			"xpos"			"280"
			"ypos"			"14"
			"zpos"			"5"
			"wide"			"40"
			"tall"			"40"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleImage"	"1"	
			"color_outline"	"52 48 45 255"
		}
		"RedLeaderAvatarBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"RedLeaderAvatarBG"
			"xpos"			"278"
			"ypos"			"12"
			"zpos"			"4"
			"wide"			"44"
			"tall"			"44"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"bgcolor_override"	"117 107 94 255"
		}
	}

	"WinPanelBGBorder"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"WinPanelBGBorder"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}

	"NewWinPanelBGBorder"
	{
		"ControlName"	"Panel"
		"fieldName"		"NewWinPanelBGBorder"
		"xpos"			"cs-0.5"
		"ypos"			"rs1-12"
		"zpos"			"0"
		"wide"			"210"	
		"tall"			"155"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"		"1"	
		"proportionaltoparent"	"1"
		"bgcolor_override"	"TransparentBlack"
		"paintBackgroundType"	"2"
	}

	"WinningTeamLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"WinningTeamLabel"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"cs-0.5"
		"ypos"			"r166"
		"zpos"			"1"
		"wide"			"f20"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
	}
	"WinningTeamLabelDropshadow"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"WinningTeamLabelDropshadow"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"f20"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
		"fgcolor"				"Black"
		"pin_to_sibling"		"WinningTeamLabel"
	}
	"AdvancingTeamLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"AdvancingTeamLabel"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"cs-0.5"
		"ypos"			"r166"
		"zpos"			"1"
		"wide"			"f20"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%AdvancingTeamLabel%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
	}
	"AdvancingTeamLabelDropshadow"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"AdvancingTeamLabelDropshadow"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"f20"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%AdvancingTeamLabel%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
		"fgcolor"				"Black"
		"pin_to_sibling"		"AdvancingTeamLabel"
	}
	"WinReasonLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"WinReasonLabel"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"DetailsLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"DetailsLabel"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"ShadedBar"
	{
		"ControlName"	"Panel"
		"fieldName"		"ShadedBar"
		"xpos"			"cs-0.5"
		"ypos"			"r140"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"120"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"TransparentBlack"
		"proportionaltoparent"	"1"
		"PaintBackgroundType"	"2"
	}
	"TopPlayerLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"TopPlayerLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"cs-0.5"
		"ypos"			"r140"
		"zpos"			"3"
		"wide"			"190"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%TopPlayersLabel%"
		"textAlignment"		"west"
		"proportionaltoparent"	"1"
	}
	"PointsThisRoundLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"PointsThisRoundLabel"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"HorizontalLine"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"cs-0.5"
		"ypos"			"r125"
		"zpos"			"3"
		"wide"			"190"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"White"
		"PaintBackgroundType"	"0"
		"proportionaltoparent"	"1"
	}
	"Player1Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player1Badge"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"Player1Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player1Avatar"
		"xpos"			"18"
		"ypos"			"r120"
		"zpos"			"3"
		"wide"			"15"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"52 48 45 255"
	}
	"Player1Name"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Player1Name"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"82"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player1Avatar"
		"pin_to_sibling_corner"	"1"
	}
	"Player1Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Class"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player1Name"
		"pin_to_sibling_corner"	"1"
	}
	"Player1Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Score"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"30"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"pin_to_sibling"	"Player1Class"
		"pin_to_sibling_corner"	"1"
	}
	"Player2Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player2Badge"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"Player2Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player2Avatar"
		"xpos"			"18"
		"ypos"			"r100"
		"zpos"			"3"
		"wide"			"15"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"52 48 45 255"
	}
	"Player2Name"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Player2Name"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"82"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player2Avatar"
		"pin_to_sibling_corner"	"1"
	}
	"Player2Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Class"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player2Name"
		"pin_to_sibling_corner"	"1"
	}
	"Player2Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Score"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"30"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"pin_to_sibling"	"Player2Class"
		"pin_to_sibling_corner"	"1"
	}
	"Player3Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player2Badge"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"Player3Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player3Avatar"
		"xpos"			"18"
		"ypos"			"r80"
		"zpos"			"3"
		"wide"			"15"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"52 48 45 255"
	}
	"Player3Name"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Player3Name"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"82"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player3Avatar"
		"pin_to_sibling_corner"	"1"
	}
	"Player3Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Class"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"Player3Name"
		"pin_to_sibling_corner"	"1"
	}
	"Player3Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Score"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"30"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"pin_to_sibling"	"Player3Class"
		"pin_to_sibling_corner"	"1"
	}

	// KillStreak
	"KillStreakLeaderLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"KillStreakLeaderLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"cs-0.5"
		"ypos"			"r65"
		"zpos"			"3"
		"wide"			"190"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Winpanel_KillStreakLeader"
		"textAlignment"		"west"
		"proportionaltoparent"	"1"
	}
	"KillStreakMaxCountLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"KillStreakMaxCountLabel"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"HorizontalLine2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HorizontalLine2"
		"xpos"			"cs-0.5"
		"ypos"			"r50"
		"zpos"			"3"
		"wide"			"190"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"White"
		"PaintBackgroundType"	"0"
		"proportionaltoparent"	"1"
	}
	"KillStreakPlayer1Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"KillStreakPlayer1Badge"
		"xpos"			"9999"
		"wide"			"0"
		"visible"		"0"
	}
	"KillStreakPlayer1Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"KillStreakPlayer1Avatar"
		"xpos"			"18"
		"ypos"			"r42"
		"zpos"			"3"
		"wide"			"15"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"52 48 45 255"
	}
	"KillStreakPlayer1Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Name"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"82"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"KillStreakPlayer1Avatar"
		"pin_to_sibling_corner"	"1"
	}
	"KillStreakPlayer1Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Class"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"pin_to_sibling"	"KillStreakPlayer1Name"
		"pin_to_sibling_corner"	"1"
	}
	"KillStreakPlayer1Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Score"
		"xpos"			"2"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"30"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"pin_to_sibling"	"KillStreakPlayer1Class"
		"pin_to_sibling_corner"	"1"
	}
}
